"""New Columns

Revision ID: 4696b5107d0d
Revises: 
Create Date: 2020-06-03 11:32:17.135855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4696b5107d0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('people', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'last_seen')
    op.drop_column('people', 'about_me')
    # ### end Alembic commands ###
